import mongoose from "mongoose";

export const sampleUsers = [
  {
    _id: new mongoose.Types.ObjectId(),
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@acme.com",
    phone: "+1-555-123-4567",
    company: "Acme Manufacturing",
    department: "Production",
    role: "Supervisor",
    jobTitle: "Production Line Supervisor",
    experience: {
      yearsInIndustry: 8,
      expertise: ["Lean Manufacturing", "Quality Control", "Team Leadership"],
      certifications: ["Six Sigma Green Belt", "ISO 9001 Auditor"],
    },
    preferences: {
      language: "en",
      timezone: "America/New_York",
      communicationChannel: "email",
    },
    demographics: {
      ageRange: "35-44",
      gender: "male",
      education: "Bachelor's Degree",
    },
    workHistory: {
      currentPosition: "Production Line Supervisor",
      previousPositions: ["Production Operator", "Team Lead"],
      industrySpecialization: ["Automotive Manufacturing", "Quality Control"],
    },
    status: "active",
    participation: {
      surveysCompleted: 12,
      lastResponseDate: new Date("2024-01-15"),
      responseRate: 0.85,
    },
    address: {
      street: "123 Industrial Ave",
      city: "Detroit",
      state: "MI",
      country: "USA",
      postalCode: "48201",
    },
    joinedAt: new Date("2023-01-01"),
    lastActive: new Date("2024-01-15"),
    metadata: {
      shiftPreference: "morning",
      departmentCode: "PROD-01",
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@steel.com",
    phone: "+1-555-987-6543",
    company: "Steel Dynamics",
    department: "Quality Assurance",
    role: "Manager",
    jobTitle: "QA Manager",
    experience: {
      yearsInIndustry: 12,
      expertise: [
        "Quality Management",
        "Process Optimization",
        "Regulatory Compliance",
      ],
      certifications: ["Six Sigma Black Belt", "ASQ Certified Manager"],
    },
    preferences: {
      language: "en",
      timezone: "America/Chicago",
      communicationChannel: "both",
    },
    demographics: {
      ageRange: "45-54",
      gender: "female",
      education: "Master's Degree",
    },
    workHistory: {
      currentPosition: "QA Manager",
      previousPositions: ["QA Specialist", "Manufacturing Engineer"],
      industrySpecialization: ["Steel Manufacturing", "Process Control"],
    },
    status: "active",
    participation: {
      surveysCompleted: 24,
      lastResponseDate: new Date("2024-01-20"),
      responseRate: 0.92,
    },
    address: {
      street: "456 Steel Mill Rd",
      city: "Gary",
      state: "IN",
      country: "USA",
      postalCode: "46404",
    },
    joinedAt: new Date("2022-06-15"),
    lastActive: new Date("2024-01-20"),
    metadata: {
      specializations: ["Heat Treatment", "Metal Testing"],
      projectLead: true,
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    firstName: "Michael",
    lastName: "Chen",
    email: "m.chen@tech.com",
    phone: "+1-555-789-0123",
    company: "Tech Manufacturing Solutions",
    department: "Engineering",
    role: "Engineer",
    jobTitle: "Process Engineer",
    experience: {
      yearsInIndustry: 5,
      expertise: ["Automation", "robotics", "PLC Programming"],
      certifications: ["Professional Engineer", "Automation Certified Expert"],
    },
    preferences: {
      language: "en",
      timezone: "America/Los_Angeles",
      communicationChannel: "email",
    },
    demographics: {
      ageRange: "25-34",
      gender: "male",
      education: "Master's Degree",
    },
    workHistory: {
      currentPosition: "Process Engineer",
      previousPositions: ["Junior Engineer", "Engineering Intern"],
      industrySpecialization: ["Electronics Manufacturing", "Automation"],
    },
    status: "active",
    participation: {
      surveysCompleted: 8,
      lastResponseDate: new Date("2024-01-18"),
      responseRate: 0.75,
    },
    address: {
      street: "789 Tech Park Way",
      city: "San Jose",
      state: "CA",
      country: "USA",
      postalCode: "95110",
    },
    joinedAt: new Date("2023-03-15"),
    lastActive: new Date("2024-01-18"),
    metadata: {
      projectAreas: ["Automation", "Process Optimization"],
      teamSize: 5,
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    firstName: "Emily",
    lastName: "Davis",
    email: "e.davis@precision.com",
    phone: "+1-555-456-7890",
    company: "Precision Machining Inc.",
    department: "Manufacturing",
    role: "CNC Operator",
    jobTitle: "CNC Machinist",
    experience: {
      yearsInIndustry: 3,
      expertise: ["CNC Programming", "Precision Machining", "Metrology"],
      certifications: ["NIMS Level 1 CNC Operator"],
    },
    preferences: {
      language: "en",
      timezone: "America/Chicago",
      communicationChannel: "email",
    },
    demographics: {
      ageRange: "22-29",
      gender: "female",
      education: "Associate's Degree",
    },
    workHistory: {
      currentPosition: "CNC Machinist",
      previousPositions: ["Machine Operator", "Shop Assistant"],
      industrySpecialization: ["Precision Manufacturing", "Quality Control"],
    },
    status: "active",
    participation: {
      surveysCompleted: 5,
      lastResponseDate: new Date("2024-01-12"),
      responseRate: 0.8,
    },
    address: {
      street: "321 Factory Rd",
      city: "Chicago",
      state: "IL",
      country: "USA",
      postalCode: "60601",
    },
    joinedAt: new Date("2023-07-01"),
    lastActive: new Date("2024-01-12"),
    metadata: {
      trainingNeeds: ["Lean Manufacturing", "Geometric Dimensioning"],
      specialEquipment: ["Coordinate Measuring Machine"],
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    firstName: "David",
    lastName: "Lee",
    email: "d.lee@aero.com",
    phone: "+1-555-987-2345",
    company: "Aerospace Manufacturing",
    department: "Engineering",
    role: "Design Engineer",
    jobTitle: "Aerospace Design Engineer",
    experience: {
      yearsInIndustry: 10,
      expertise: ["CAD Modeling", "Structural Analysis", "Aerodynamics"],
      certifications: [
        "Professional Engineering License",
        "CATIA Certification",
      ],
    },
    preferences: {
      language: "en",
      timezone: "America/Los_Angeles",
      communicationChannel: "both",
    },
    demographics: {
      ageRange: "35-44",
      gender: "male",
      education: "Master's Degree",
    },
    workHistory: {
      currentPosition: "Aerospace Design Engineer",
      previousPositions: ["Systems Engineer", "Design Intern"],
      industrySpecialization: ["Aerospace Manufacturing", "Composites"],
    },
    status: "active",
    participation: {
      surveysCompleted: 18,
      lastResponseDate: new Date("2024-01-25"),
      responseRate: 0.9,
    },
    address: {
      street: "987 Aerospace Blvd",
      city: "Los Angeles",
      state: "CA",
      country: "USA",
      postalCode: "90001",
    },
    joinedAt: new Date("2021-09-01"),
    lastActive: new Date("2024-01-25"),
    metadata: {
      projects: ["Next-Gen Fighter Jet", "Satellite Structures"],
      securityClearance: "Secret",
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    firstName: "Samantha",
    lastName: "Rodriguez",
    email: "s.rodriguez@food.com",
    phone: "+1-555-654-3210",
    company: "FoodCo Manufacturing",
    department: "Quality Control",
    role: "Inspector",
    jobTitle: "Quality Inspector",
    experience: {
      yearsInIndustry: 6,
      expertise: ["Food Safety", "Regulatory Compliance", "Auditing"],
      certifications: ["HACCP Certified", "ISO 22000 Lead Auditor"],
    },
    preferences: {
      language: "en",
      timezone: "America/New_York",
      communicationChannel: "both",
    },
    demographics: {
      ageRange: "30-39",
      gender: "female",
      education: "Bachelor's Degree",
    },
    workHistory: {
      currentPosition: "Quality Inspector",
      previousPositions: ["Quality Technician", "Production Worker"],
      industrySpecialization: ["Food Manufacturing", "Quality Assurance"],
    },
    status: "active",
    participation: {
      surveysCompleted: 15,
      lastResponseDate: new Date("2024-01-22"),
      responseRate: 0.88,
    },
    address: {
      street: "654 Food Processing Rd",
      city: "New York",
      state: "NY",
      country: "USA",
      postalCode: "10001",
    },
    joinedAt: new Date("2022-11-01"),
    lastActive: new Date("2024-01-22"),
    metadata: {
      trainings: ["Sensory Evaluation", "Advanced Food Microbiology"],
      fluentLanguages: ["English", "Spanish"],
    },
  },
];

const user1Id = sampleUsers[0]._id;
const user2Id = sampleUsers[1]._id;
const user3Id = sampleUsers[2]._id;
const user4Id = sampleUsers[3]._id;
const user5Id = sampleUsers[4]._id;

export const sampleManufacturers = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Acme Manufacturing",
    industry: "Automotive",
    userIds: [user1Id, user2Id],
    contactPerson: {
      name: "Robert Johnson",
      email: "r.johnson@acme.com",
      phone: "+1-555-111-2222",
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Steel Dynamics",
    industry: "Steel",
    userIds: [user2Id, user3Id],
    contactPerson: {
      name: "Sarah Williams",
      email: "s.williams@steel.com",
      phone: "+1-555-333-4444",
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Tech Manufacturing Solutions",
    industry: "Electronics",
    userIds: [user3Id, user4Id, user1Id],
    contactPerson: {
      name: "Jennifer Chen",
      email: "j.chen@tech.com",
      phone: "+1-555-777-8888",
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Precision Machining Inc.",
    industry: "Machining",
    userIds: [user4Id],
    contactPerson: {
      name: "Michael Thompson",
      email: "m.thompson@precision.com",
      phone: "+1-555-222-3333",
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "Aerospace Manufacturing",
    industry: "Aerospace",
    userIds: [user5Id, user2Id, user4Id],
    contactPerson: {
      name: "Emily Chen",
      email: "e.chen@aero.com",
      phone: "+1-555-444-5555",
    },
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: "FoodCo Manufacturing",
    industry: "Food",
    userIds: [user5Id, user1Id],
    contactPerson: {
      name: "Juan Gonzalez",
      email: "j.gonzalez@food.com",
      phone: "+1-555-999-0000",
    },
  },
];
